[package]
name = "nix-pins"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
ctrlc = { version = "3.1.4", default-features = false }
crossterm = "0.29"
fs2 = "0.4"
libc = "0.2"
prodash = { version = "31", default-features = false, features = ["progress-tree", "unit-bytes", "unit-human"] }
ratatui = { version = "0.30", default-features = false, features = ["crossterm"] }
regex = "1.11"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
semver = "1.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
unicode-width = "0.2"
config = { version = "0.15", default-features = false, features = ["toml"] }
